apiVersion: upcloud.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      name: upcloud-creds
      namespace: crossplane-system
      key: creds
