apiVersion: storage.upcloud.crossplane.io/v1alpha1
kind: Storage
metadata:
  annotations:
    meta.upbound.io/example-id: storage/v1alpha1/storage
  labels:
    testing.upbound.io/example-name: storage-example
  name: storage-example
spec:
  forProvider:
    size: 10
    tier: standard
    title: storage-example
    zone: fi-hel2
  providerConfigRef:
    name: default
