// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type ServerPrivateFirewallRulesetInitParameters struct {

	// (String) The UUID of the firewall ruleset to attach.
	// The UUID of the firewall ruleset to attach.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upcloud/apis/namespaced/network/v1alpha1.FirewallRuleset
	RulesetID *string `json:"rulesetId,omitempty" tf:"ruleset_id,omitempty"`

	// Reference to a FirewallRuleset in network to populate rulesetId.
	// +kubebuilder:validation:Optional
	RulesetIDRef *v2.NamespacedReference `json:"rulesetIdRef,omitempty" tf:"-"`

	// Selector for a FirewallRuleset in network to populate rulesetId.
	// +kubebuilder:validation:Optional
	RulesetIDSelector *v2.NamespacedSelector `json:"rulesetIdSelector,omitempty" tf:"-"`

	// (String) The UUID of the server to attach the firewall ruleset to.
	// The UUID of the server to attach the firewall ruleset to.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upcloud/apis/namespaced/server/v1alpha1.Server
	ServerID *string `json:"serverId,omitempty" tf:"server_id,omitempty"`

	// Reference to a Server in server to populate serverId.
	// +kubebuilder:validation:Optional
	ServerIDRef *v2.NamespacedReference `json:"serverIdRef,omitempty" tf:"-"`

	// Selector for a Server in server to populate serverId.
	// +kubebuilder:validation:Optional
	ServerIDSelector *v2.NamespacedSelector `json:"serverIdSelector,omitempty" tf:"-"`
}

type ServerPrivateFirewallRulesetObservation struct {

	// (String) Composite identifier in format {server_id}/{ruleset_id}.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The UUID of the firewall ruleset to attach.
	// The UUID of the firewall ruleset to attach.
	RulesetID *string `json:"rulesetId,omitempty" tf:"ruleset_id,omitempty"`

	// (String) The UUID of the server to attach the firewall ruleset to.
	// The UUID of the server to attach the firewall ruleset to.
	ServerID *string `json:"serverId,omitempty" tf:"server_id,omitempty"`
}

type ServerPrivateFirewallRulesetParameters struct {

	// (String) The UUID of the firewall ruleset to attach.
	// The UUID of the firewall ruleset to attach.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upcloud/apis/namespaced/network/v1alpha1.FirewallRuleset
	// +kubebuilder:validation:Optional
	RulesetID *string `json:"rulesetId,omitempty" tf:"ruleset_id,omitempty"`

	// Reference to a FirewallRuleset in network to populate rulesetId.
	// +kubebuilder:validation:Optional
	RulesetIDRef *v2.NamespacedReference `json:"rulesetIdRef,omitempty" tf:"-"`

	// Selector for a FirewallRuleset in network to populate rulesetId.
	// +kubebuilder:validation:Optional
	RulesetIDSelector *v2.NamespacedSelector `json:"rulesetIdSelector,omitempty" tf:"-"`

	// (String) The UUID of the server to attach the firewall ruleset to.
	// The UUID of the server to attach the firewall ruleset to.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upcloud/apis/namespaced/server/v1alpha1.Server
	// +kubebuilder:validation:Optional
	ServerID *string `json:"serverId,omitempty" tf:"server_id,omitempty"`

	// Reference to a Server in server to populate serverId.
	// +kubebuilder:validation:Optional
	ServerIDRef *v2.NamespacedReference `json:"serverIdRef,omitempty" tf:"-"`

	// Selector for a Server in server to populate serverId.
	// +kubebuilder:validation:Optional
	ServerIDSelector *v2.NamespacedSelector `json:"serverIdSelector,omitempty" tf:"-"`
}

// ServerPrivateFirewallRulesetSpec defines the desired state of ServerPrivateFirewallRuleset
type ServerPrivateFirewallRulesetSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ServerPrivateFirewallRulesetParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ServerPrivateFirewallRulesetInitParameters `json:"initProvider,omitempty"`
}

// ServerPrivateFirewallRulesetStatus defines the observed state of ServerPrivateFirewallRuleset.
type ServerPrivateFirewallRulesetStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               ServerPrivateFirewallRulesetObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ServerPrivateFirewallRuleset is the Schema for the ServerPrivateFirewallRulesets API. This resource represents an attachment of an UpCloud SDN private firewall ruleset to a server.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,upcloud}
type ServerPrivateFirewallRuleset struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              ServerPrivateFirewallRulesetSpec   `json:"spec"`
	Status            ServerPrivateFirewallRulesetStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ServerPrivateFirewallRulesetList contains a list of ServerPrivateFirewallRulesets
type ServerPrivateFirewallRulesetList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ServerPrivateFirewallRuleset `json:"items"`
}

// Repository type metadata.
var (
	ServerPrivateFirewallRuleset_Kind             = "ServerPrivateFirewallRuleset"
	ServerPrivateFirewallRuleset_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ServerPrivateFirewallRuleset_Kind}.String()
	ServerPrivateFirewallRuleset_KindAPIVersion   = ServerPrivateFirewallRuleset_Kind + "." + CRDGroupVersion.String()
	ServerPrivateFirewallRuleset_GroupVersionKind = CRDGroupVersion.WithKind(ServerPrivateFirewallRuleset_Kind)
)

func init() {
	SchemeBuilder.Register(&ServerPrivateFirewallRuleset{}, &ServerPrivateFirewallRulesetList{})
}
