// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type TagInitParameters struct {

	// Free form text representing the meaning of the tag.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// A collection of servers that have been assigned the tag.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upcloud/apis/namespaced/server/v1alpha1.Server
	// +listType=set
	Servers []*string `json:"servers,omitempty" tf:"servers,omitempty"`

	// References to Server in server to populate servers.
	// +kubebuilder:validation:Optional
	ServersRefs []v2.NamespacedReference `json:"serversRefs,omitempty" tf:"-"`

	// Selector for a list of Server in server to populate servers.
	// +kubebuilder:validation:Optional
	ServersSelector *v2.NamespacedSelector `json:"serversSelector,omitempty" tf:"-"`
}

type TagObservation struct {

	// Free form text representing the meaning of the tag.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// A collection of servers that have been assigned the tag.
	// +listType=set
	Servers []*string `json:"servers,omitempty" tf:"servers,omitempty"`
}

type TagParameters struct {

	// Free form text representing the meaning of the tag.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// A collection of servers that have been assigned the tag.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upcloud/apis/namespaced/server/v1alpha1.Server
	// +kubebuilder:validation:Optional
	// +listType=set
	Servers []*string `json:"servers,omitempty" tf:"servers,omitempty"`

	// References to Server in server to populate servers.
	// +kubebuilder:validation:Optional
	ServersRefs []v2.NamespacedReference `json:"serversRefs,omitempty" tf:"-"`

	// Selector for a list of Server in server to populate servers.
	// +kubebuilder:validation:Optional
	ServersSelector *v2.NamespacedSelector `json:"serversSelector,omitempty" tf:"-"`
}

// TagSpec defines the desired state of Tag
type TagSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            TagParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider TagInitParameters `json:"initProvider,omitempty"`
}

// TagStatus defines the observed state of Tag.
type TagStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               TagObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Tag is the Schema for the Tags API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,upcloud}
type Tag struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              TagSpec   `json:"spec"`
	Status            TagStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// TagList contains a list of Tags
type TagList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Tag `json:"items"`
}

// Repository type metadata.
var (
	Tag_Kind             = "Tag"
	Tag_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Tag_Kind}.String()
	Tag_KindAPIVersion   = Tag_Kind + "." + CRDGroupVersion.String()
	Tag_GroupVersionKind = CRDGroupVersion.WithKind(Tag_Kind)
)

func init() {
	SchemeBuilder.Register(&Tag{}, &TagList{})
}
