apiVersion: objectstorage.upcloud.m.crossplane.io/v1alpha1
kind: ManagedObjectStorageUserPolicy
metadata:
  annotations:
    meta.upbound.io/example-id: objectstorage/v1alpha1/managedobjectstorageuserpolicy
  labels:
    testing.upbound.io/example-name: userpolicy-example
  name: userpolicy-example
  namespace: crossplane-system
spec:
  forProvider:
    serviceUuidRef:
      name: userpolicy-example-service
    usernameRef:
      name: userpolicy-example-user
    nameRef:
      name: userpolicy-example-policy
  providerConfigRef:
    kind: ClusterProviderConfig
    name: default

---
apiVersion: objectstorage.upcloud.m.crossplane.io/v1alpha1
kind: ManagedObjectStoragePolicy
metadata:
  annotations:
    meta.upbound.io/example-id: objectstorage/v1alpha1/managedobjectstorageuserpolicy
  labels:
    testing.upbound.io/example-name: userpolicy-example-policy
  name: userpolicy-example-policy
  namespace: crossplane-system
spec:
  forProvider:
    description: example policy
    document: '%7B%22Version%22%3A%222012-10-17%22%2C%22Statement%22%3A%5B%7B%22Action%22%3A%5B%22iam%3AGetUser%22%5D%2C%22Resource%22%3A%22*%22%2C%22Effect%22%3A%22Allow%22%2C%22Sid%22%3A%22editor%22%7D%5D%7D'
    serviceUuidRef:
      name: userpolicy-example-service
  providerConfigRef:
    kind: ClusterProviderConfig
    name: default

---
apiVersion: objectstorage.upcloud.m.crossplane.io/v1alpha1
kind: ManagedObjectStorageUser
metadata:
  annotations:
    meta.upbound.io/example-id: objectstorage/v1alpha1/managedobjectstorageuserpolicy
  labels:
    testing.upbound.io/example-name: userpolicy-example-user
  name: userpolicy-example-user
  namespace: crossplane-system
spec:
  forProvider:
    serviceUuidRef:
      name: userpolicy-example-service
  providerConfigRef:
    kind: ClusterProviderConfig
    name: default

---
apiVersion: objectstorage.upcloud.m.crossplane.io/v1alpha1
kind: ManagedObjectStorage
metadata:
  annotations:
    meta.upbound.io/example-id: objectstorage/v1alpha1/managedobjectstorageuserpolicy
  labels:
    testing.upbound.io/example-name: userpolicy-example-service
  name: userpolicy-example-service
  namespace: crossplane-system
spec:
  forProvider:
    name: userpolicy-example-service
    region: europe-1
    configuredStatus: started
  providerConfigRef:
    kind: ClusterProviderConfig
    name: default
