// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"

// GetCondition of this ManagedDatabaseLogicalDatabase.
func (mg *ManagedDatabaseLogicalDatabase) GetCondition(ct xpv2.ConditionType) xpv2.Condition {
	return mg.Status.GetCondition(ct)
}

// GetDeletionPolicy of this ManagedDatabaseLogicalDatabase.
func (mg *ManagedDatabaseLogicalDatabase) GetDeletionPolicy() xpv2.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetManagementPolicies of this ManagedDatabaseLogicalDatabase.
func (mg *ManagedDatabaseLogicalDatabase) GetManagementPolicies() xpv2.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this ManagedDatabaseLogicalDatabase.
func (mg *ManagedDatabaseLogicalDatabase) GetProviderConfigReference() *xpv2.Reference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this ManagedDatabaseLogicalDatabase.
func (mg *ManagedDatabaseLogicalDatabase) GetWriteConnectionSecretToReference() *xpv2.SecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this ManagedDatabaseLogicalDatabase.
func (mg *ManagedDatabaseLogicalDatabase) SetConditions(c ...xpv2.Condition) {
	mg.Status.SetConditions(c...)
}

// SetDeletionPolicy of this ManagedDatabaseLogicalDatabase.
func (mg *ManagedDatabaseLogicalDatabase) SetDeletionPolicy(r xpv2.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetManagementPolicies of this ManagedDatabaseLogicalDatabase.
func (mg *ManagedDatabaseLogicalDatabase) SetManagementPolicies(r xpv2.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this ManagedDatabaseLogicalDatabase.
func (mg *ManagedDatabaseLogicalDatabase) SetProviderConfigReference(r *xpv2.Reference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this ManagedDatabaseLogicalDatabase.
func (mg *ManagedDatabaseLogicalDatabase) SetWriteConnectionSecretToReference(r *xpv2.SecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this ManagedDatabaseMysql.
func (mg *ManagedDatabaseMysql) GetCondition(ct xpv2.ConditionType) xpv2.Condition {
	return mg.Status.GetCondition(ct)
}

// GetDeletionPolicy of this ManagedDatabaseMysql.
func (mg *ManagedDatabaseMysql) GetDeletionPolicy() xpv2.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetManagementPolicies of this ManagedDatabaseMysql.
func (mg *ManagedDatabaseMysql) GetManagementPolicies() xpv2.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this ManagedDatabaseMysql.
func (mg *ManagedDatabaseMysql) GetProviderConfigReference() *xpv2.Reference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this ManagedDatabaseMysql.
func (mg *ManagedDatabaseMysql) GetWriteConnectionSecretToReference() *xpv2.SecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this ManagedDatabaseMysql.
func (mg *ManagedDatabaseMysql) SetConditions(c ...xpv2.Condition) {
	mg.Status.SetConditions(c...)
}

// SetDeletionPolicy of this ManagedDatabaseMysql.
func (mg *ManagedDatabaseMysql) SetDeletionPolicy(r xpv2.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetManagementPolicies of this ManagedDatabaseMysql.
func (mg *ManagedDatabaseMysql) SetManagementPolicies(r xpv2.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this ManagedDatabaseMysql.
func (mg *ManagedDatabaseMysql) SetProviderConfigReference(r *xpv2.Reference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this ManagedDatabaseMysql.
func (mg *ManagedDatabaseMysql) SetWriteConnectionSecretToReference(r *xpv2.SecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this ManagedDatabaseOpensearch.
func (mg *ManagedDatabaseOpensearch) GetCondition(ct xpv2.ConditionType) xpv2.Condition {
	return mg.Status.GetCondition(ct)
}

// GetDeletionPolicy of this ManagedDatabaseOpensearch.
func (mg *ManagedDatabaseOpensearch) GetDeletionPolicy() xpv2.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetManagementPolicies of this ManagedDatabaseOpensearch.
func (mg *ManagedDatabaseOpensearch) GetManagementPolicies() xpv2.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this ManagedDatabaseOpensearch.
func (mg *ManagedDatabaseOpensearch) GetProviderConfigReference() *xpv2.Reference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this ManagedDatabaseOpensearch.
func (mg *ManagedDatabaseOpensearch) GetWriteConnectionSecretToReference() *xpv2.SecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this ManagedDatabaseOpensearch.
func (mg *ManagedDatabaseOpensearch) SetConditions(c ...xpv2.Condition) {
	mg.Status.SetConditions(c...)
}

// SetDeletionPolicy of this ManagedDatabaseOpensearch.
func (mg *ManagedDatabaseOpensearch) SetDeletionPolicy(r xpv2.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetManagementPolicies of this ManagedDatabaseOpensearch.
func (mg *ManagedDatabaseOpensearch) SetManagementPolicies(r xpv2.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this ManagedDatabaseOpensearch.
func (mg *ManagedDatabaseOpensearch) SetProviderConfigReference(r *xpv2.Reference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this ManagedDatabaseOpensearch.
func (mg *ManagedDatabaseOpensearch) SetWriteConnectionSecretToReference(r *xpv2.SecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this ManagedDatabasePostgresql.
func (mg *ManagedDatabasePostgresql) GetCondition(ct xpv2.ConditionType) xpv2.Condition {
	return mg.Status.GetCondition(ct)
}

// GetDeletionPolicy of this ManagedDatabasePostgresql.
func (mg *ManagedDatabasePostgresql) GetDeletionPolicy() xpv2.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetManagementPolicies of this ManagedDatabasePostgresql.
func (mg *ManagedDatabasePostgresql) GetManagementPolicies() xpv2.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this ManagedDatabasePostgresql.
func (mg *ManagedDatabasePostgresql) GetProviderConfigReference() *xpv2.Reference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this ManagedDatabasePostgresql.
func (mg *ManagedDatabasePostgresql) GetWriteConnectionSecretToReference() *xpv2.SecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this ManagedDatabasePostgresql.
func (mg *ManagedDatabasePostgresql) SetConditions(c ...xpv2.Condition) {
	mg.Status.SetConditions(c...)
}

// SetDeletionPolicy of this ManagedDatabasePostgresql.
func (mg *ManagedDatabasePostgresql) SetDeletionPolicy(r xpv2.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetManagementPolicies of this ManagedDatabasePostgresql.
func (mg *ManagedDatabasePostgresql) SetManagementPolicies(r xpv2.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this ManagedDatabasePostgresql.
func (mg *ManagedDatabasePostgresql) SetProviderConfigReference(r *xpv2.Reference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this ManagedDatabasePostgresql.
func (mg *ManagedDatabasePostgresql) SetWriteConnectionSecretToReference(r *xpv2.SecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this ManagedDatabaseUser.
func (mg *ManagedDatabaseUser) GetCondition(ct xpv2.ConditionType) xpv2.Condition {
	return mg.Status.GetCondition(ct)
}

// GetDeletionPolicy of this ManagedDatabaseUser.
func (mg *ManagedDatabaseUser) GetDeletionPolicy() xpv2.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetManagementPolicies of this ManagedDatabaseUser.
func (mg *ManagedDatabaseUser) GetManagementPolicies() xpv2.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this ManagedDatabaseUser.
func (mg *ManagedDatabaseUser) GetProviderConfigReference() *xpv2.Reference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this ManagedDatabaseUser.
func (mg *ManagedDatabaseUser) GetWriteConnectionSecretToReference() *xpv2.SecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this ManagedDatabaseUser.
func (mg *ManagedDatabaseUser) SetConditions(c ...xpv2.Condition) {
	mg.Status.SetConditions(c...)
}

// SetDeletionPolicy of this ManagedDatabaseUser.
func (mg *ManagedDatabaseUser) SetDeletionPolicy(r xpv2.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetManagementPolicies of this ManagedDatabaseUser.
func (mg *ManagedDatabaseUser) SetManagementPolicies(r xpv2.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this ManagedDatabaseUser.
func (mg *ManagedDatabaseUser) SetProviderConfigReference(r *xpv2.Reference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this ManagedDatabaseUser.
func (mg *ManagedDatabaseUser) SetWriteConnectionSecretToReference(r *xpv2.SecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this ManagedDatabaseValkey.
func (mg *ManagedDatabaseValkey) GetCondition(ct xpv2.ConditionType) xpv2.Condition {
	return mg.Status.GetCondition(ct)
}

// GetDeletionPolicy of this ManagedDatabaseValkey.
func (mg *ManagedDatabaseValkey) GetDeletionPolicy() xpv2.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetManagementPolicies of this ManagedDatabaseValkey.
func (mg *ManagedDatabaseValkey) GetManagementPolicies() xpv2.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this ManagedDatabaseValkey.
func (mg *ManagedDatabaseValkey) GetProviderConfigReference() *xpv2.Reference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this ManagedDatabaseValkey.
func (mg *ManagedDatabaseValkey) GetWriteConnectionSecretToReference() *xpv2.SecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this ManagedDatabaseValkey.
func (mg *ManagedDatabaseValkey) SetConditions(c ...xpv2.Condition) {
	mg.Status.SetConditions(c...)
}

// SetDeletionPolicy of this ManagedDatabaseValkey.
func (mg *ManagedDatabaseValkey) SetDeletionPolicy(r xpv2.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetManagementPolicies of this ManagedDatabaseValkey.
func (mg *ManagedDatabaseValkey) SetManagementPolicies(r xpv2.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this ManagedDatabaseValkey.
func (mg *ManagedDatabaseValkey) SetProviderConfigReference(r *xpv2.Reference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this ManagedDatabaseValkey.
func (mg *ManagedDatabaseValkey) SetWriteConnectionSecretToReference(r *xpv2.SecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}
