// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type StorageBackupInitParameters struct {

	// value pairs to classify the storage.
	// User defined key-value pairs to classify the storage.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String) The UUID of the storage to back up.
	// The UUID of the storage to back up.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upcloud/apis/cluster/storage/v1alpha1.Storage
	SourceStorage *string `json:"sourceStorage,omitempty" tf:"source_storage,omitempty"`

	// Reference to a Storage in storage to populate sourceStorage.
	// +kubebuilder:validation:Optional
	SourceStorageRef *v2.Reference `json:"sourceStorageRef,omitempty" tf:"-"`

	// Selector for a Storage in storage to populate sourceStorage.
	// +kubebuilder:validation:Optional
	SourceStorageSelector *v2.Selector `json:"sourceStorageSelector,omitempty" tf:"-"`

	// (String) Title of the backup.
	// Title of the backup.
	Title *string `json:"title,omitempty" tf:"title,omitempty"`
}

type StorageBackupObservation struct {

	// (String) Timestamp of the backup creation.
	// Timestamp of the backup creation.
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// (Boolean) Sets if the storage is encrypted at rest.
	// Sets if the storage is encrypted at rest.
	Encrypt *bool `json:"encrypt,omitempty" tf:"encrypt,omitempty"`

	// (String) ID of the created backup.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// value pairs to classify the storage.
	// User defined key-value pairs to classify the storage.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (Number) The size of the storage in gigabytes.
	// The size of the storage in gigabytes.
	Size *float64 `json:"size,omitempty" tf:"size,omitempty"`

	// (String) The UUID of the storage to back up.
	// The UUID of the storage to back up.
	SourceStorage *string `json:"sourceStorage,omitempty" tf:"source_storage,omitempty"`

	// value pairs to classify the storage. The keys of system defined labels are prefixed with underscore and can not be modified by the user.
	// System defined key-value pairs to classify the storage. The keys of system defined labels are prefixed with underscore and can not be modified by the user.
	// +mapType=granular
	SystemLabels map[string]*string `json:"systemLabels,omitempty" tf:"system_labels,omitempty"`

	// (String) The tier of the storage.
	// The tier of the storage.
	Tier *string `json:"tier,omitempty" tf:"tier,omitempty"`

	// (String) Title of the backup.
	// Title of the backup.
	Title *string `json:"title,omitempty" tf:"title,omitempty"`

	// (String) The type of the storage.
	// The type of the storage.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// fra1.
	// The zone the storage is in, e.g. `de-fra1`.
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type StorageBackupParameters struct {

	// value pairs to classify the storage.
	// User defined key-value pairs to classify the storage.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String) The UUID of the storage to back up.
	// The UUID of the storage to back up.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upcloud/apis/cluster/storage/v1alpha1.Storage
	// +kubebuilder:validation:Optional
	SourceStorage *string `json:"sourceStorage,omitempty" tf:"source_storage,omitempty"`

	// Reference to a Storage in storage to populate sourceStorage.
	// +kubebuilder:validation:Optional
	SourceStorageRef *v2.Reference `json:"sourceStorageRef,omitempty" tf:"-"`

	// Selector for a Storage in storage to populate sourceStorage.
	// +kubebuilder:validation:Optional
	SourceStorageSelector *v2.Selector `json:"sourceStorageSelector,omitempty" tf:"-"`

	// (String) Title of the backup.
	// Title of the backup.
	// +kubebuilder:validation:Optional
	Title *string `json:"title,omitempty" tf:"title,omitempty"`
}

// StorageBackupSpec defines the desired state of StorageBackup
type StorageBackupSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   StorageBackupParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider StorageBackupInitParameters `json:"initProvider,omitempty"`
}

// StorageBackupStatus defines the observed state of StorageBackup.
type StorageBackupStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               StorageBackupObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// StorageBackup is the Schema for the StorageBackups API. Manages an on-demand storage backup.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,upcloud}
type StorageBackup struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.title) || (has(self.initProvider) && has(self.initProvider.title))",message="spec.forProvider.title is a required parameter"
	Spec   StorageBackupSpec   `json:"spec"`
	Status StorageBackupStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// StorageBackupList contains a list of StorageBackups
type StorageBackupList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []StorageBackup `json:"items"`
}

// Repository type metadata.
var (
	StorageBackup_Kind             = "StorageBackup"
	StorageBackup_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: StorageBackup_Kind}.String()
	StorageBackup_KindAPIVersion   = StorageBackup_Kind + "." + CRDGroupVersion.String()
	StorageBackup_GroupVersionKind = CRDGroupVersion.WithKind(StorageBackup_Kind)
)

func init() {
	SchemeBuilder.Register(&StorageBackup{}, &StorageBackupList{})
}
