apiVersion: uks.upcloud.m.crossplane.io/v1alpha1
kind: KubernetesCluster
metadata:
  annotations:
    meta.upbound.io/example-id: uks/v1alpha1/kubernetescluster
  labels:
    testing.upbound.io/example-name: uks-example
  name: uks-example
  namespace: crossplane-system
spec:
  forProvider:
    name: uks-example
    zone: de-fra1
    controlPlaneIpFilter:
      - 0.0.0.0/0
    labels: {}
    networkRef:
      name: uks-example-network
  providerConfigRef:
    kind: ClusterProviderConfig
    name: default

---
apiVersion: network.upcloud.m.crossplane.io/v1alpha1
kind: Network
metadata:
  annotations:
    meta.upbound.io/example-id: uks/v1alpha1/kubernetescluster
  labels:
    testing.upbound.io/example-name: uks-example-network
  name: uks-example-network
  namespace: crossplane-system
spec:
  forProvider:
    name: uks-example-network
    zone: de-fra1
    ipNetwork:
      - address: 172.16.1.0/24
        dhcp: true
        family: IPv4
  providerConfigRef:
    kind: ClusterProviderConfig
    name: default
