apiVersion: network.upcloud.m.crossplane.io/v1alpha1
kind: FirewallRuleset
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1alpha1/firewallruleset
  labels:
    testing.upbound.io/example-name: firewallruleset-example
  name: firewallruleset-example
  namespace: crossplane-system
spec:
  forProvider:
    name: firewallruleset-example
    description: example ruleset
    defaultDnsRulesEnabled: true
    labels:
      environment: example
  providerConfigRef:
    kind: ClusterProviderConfig
    name: default
