apiVersion: network.upcloud.m.crossplane.io/v1alpha1
kind: FloatingIPAddress
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1alpha1/floatingipaddress
  labels:
    testing.upbound.io/example-name: floatingip-example
  name: floatingip-example
  namespace: crossplane-system
spec:
  forProvider:
    zone: fi-hel2
    macAddressRef:
      name: floatingip-example-server
  providerConfigRef:
    kind: ClusterProviderConfig
    name: default

---
apiVersion: server.upcloud.m.crossplane.io/v1alpha1
kind: Server
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1alpha1/floatingipaddress
  labels:
    testing.upbound.io/example-name: floatingip-example-server
  name: floatingip-example-server
  namespace: crossplane-system
spec:
  forProvider:
    hostname: floatingip-example-server
    title: floatingip-example-server
    plan: 1xCPU-1GB
    zone: fi-hel2
    metadata: true
    login:
      user: example
    networkInterface:
      - type: public
    template:
      size: 25
      storage: Ubuntu Server 24.04 LTS (Noble Numbat)
  providerConfigRef:
    kind: ClusterProviderConfig
    name: default
