apiVersion: network.upcloud.m.crossplane.io/v1alpha1
kind: LoadBalancerFrontendTLSConfig
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1alpha1/loadbalancerfrontendtlsconfig
  labels:
    testing.upbound.io/example-name: lbfetls-example
  name: lbfetls-example
  namespace: crossplane-system
spec:
  forProvider:
    frontendRef:
      name: lbfetls-example-frontend
    certificateBundleRef:
      name: lbfetls-example-bundle
  providerConfigRef:
    kind: ClusterProviderConfig
    name: default

---
apiVersion: network.upcloud.m.crossplane.io/v1alpha1
kind: LoadBalancerManualCertificateBundle
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1alpha1/loadbalancerfrontendtlsconfig
  labels:
    testing.upbound.io/example-name: lbfetls-example-bundle
  name: lbfetls-example-bundle
  namespace: crossplane-system
spec:
  forProvider:
    name: lbfetls-example-bundle
    certificate: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURDekNDQWZPZ0F3SUJBZ0lVSnduR0dVeDJCeVFNZmVWcEZJVEFzUkI5dkxBd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0ZURVRNQkVHQTFVRUF3d0tiR0l1WlhoaGJYQnNaVEFlRncweU5qQTVNamd3T0RBd01UWmFGdzB6TmpBNQpNalV3T0RBd01UWmFNQlV4RXpBUkJnTlZCQU1NQ214aUxtVjRZVzF3YkdVd2dnRWlNQTBHQ1NxR1NJYjNEUUVCCkFRVUFBNElCRHdBd2dnRUtBb0lCQVFEYjVzdkVudWNCNFo5U3QzcVl6enAvN1FIQnNycmp6WTAvemRpWHl3enkKUys5ZlN6SHhCQWV2M1M0M1gwNXZSMGkrenMzOUZjeGRGQ0tmQlRmeDZlSFdsMnRJaTVmNVhxaHJsUnkvUlZGZAphWEdPM3pZc1czZWdQNWZwT01WV3hGaFZDU1RNTDlyN29DSWF2aDJ6WUpqQzV5YnRXQnpnR2RKRW9vYzd1anRMCjQ5V3VIZGE1U3N5UjhRYUN6bkZhT2NGWmpiazc3NVBLUTBRVVJld3dpYlNydEtjQWIzOHcwbDZiVlRkckcwcTgKWlRFQjB3Ykt2d3dDd0ptS0V4WVdmN291UkllWFJDVzFiQ0xhTjR0c2VsRk5EZHpZVFdlRWpUVnZTa0JjV3hnbQpuWk9ldm5jSXBvQk1qVldzSUp6M0Qrdk9vaitjT2ZkTTVhUmFxZTBjRFpMVkFnTUJBQUdqVXpCUk1CMEdBMVVkCkRnUVdCQlNhYkV0Wk0vSGRXN0ZpQ0lPYUpHa25yeTVRQ1RBZkJnTlZIU01FR0RBV2dCU2FiRXRaTS9IZFc3RmkKQ0lPYUpHa25yeTVRQ1RBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFCbAo5NThabE9UVG1LVWxjV0M3MUxsbEZjUjFmV3FUUFVIdGtLdDJqQ1BCYm9haFlGMkE1Qjg1djY1REt0d3JXY2VmClFncVJ1bEpPQWhiUkxPU1BKRytaWU5WY0pLSkJ0SDRsa3J6UzVBWWdPTkc0TE8vNjBpbzZacVJJWHRPRm9hRDIKWmszdmYyRWwzZUoxcFcyS2JKckNFRGFxM3lBREpwRWVOcWFadEZQUWVSMzZvT1gyL0NobGFIWFJFN245UUpxRgpuTXp2QlAyN2t6MXRRa3FkM3ViVXovcTNhWWY2YmdzZ3FPWVNublBET2N6cHJEUFZOL0xjQ2ZXeENQakR1V01hCnl1RmZCdFRTYzV1aVVkVmJERmtEZ0NwVFM2dlZwZVE3RExxdU1JWlJiaGV0cFBDZ2JIVjNBcThEQjRHaC9XOGQKSlcrUC9UZEpISVc2c3ZWOE1VOTcKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    privateKeySecretRef:
      name: lbfetls-example-bundle-key
      key: privateKey
  providerConfigRef:
    kind: ClusterProviderConfig
    name: default

---
apiVersion: v1
kind: Secret
metadata:
  name: lbfetls-example-bundle-key
  namespace: crossplane-system
type: Opaque
stringData:
  privateKey: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2QUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktZd2dnU2lBZ0VBQW9JQkFRRGI1c3ZFbnVjQjRaOVMKdDNxWXp6cC83UUhCc3JyanpZMC96ZGlYeXd6eVMrOWZTekh4QkFldjNTNDNYMDV2UjBpK3pzMzlGY3hkRkNLZgpCVGZ4NmVIV2wydElpNWY1WHFocmxSeS9SVkZkYVhHTzN6WXNXM2VnUDVmcE9NVld4RmhWQ1NUTUw5cjdvQ0lhCnZoMnpZSmpDNXlidFdCemdHZEpFb29jN3VqdEw0OVd1SGRhNVNzeVI4UWFDem5GYU9jRlpqYms3NzVQS1EwUVUKUmV3d2liU3J0S2NBYjM4dzBsNmJWVGRyRzBxOFpURUIwd2JLdnd3Q3dKbUtFeFlXZjdvdVJJZVhSQ1cxYkNMYQpONHRzZWxGTkRkellUV2VFalRWdlNrQmNXeGdtblpPZXZuY0lwb0JNalZXc0lKejNEK3ZPb2orY09mZE01YVJhCnFlMGNEWkxWQWdNQkFBRUNnZ0VBQ0cvbUFKRENOMEhEWGFhWmh4Um9YN0Vsd0p0TmJXRWRHc1lZbWRaYUZFL1MKaXRyMU94U1hBT25oRkpITkRocnprUktaTjYwbTdxbFBuTDlVQXEyaEV4MHpLaERsRDFYUTYzUElxeFFMUjZTOApqU2xHU0ZSb0ZoZHFpakc1N0piUzlzeEhnNmdRWkZna0J0ZWxoeFRkTjVrcjFxNXJTVFBrYStxNmVwR3VKYjZ4ClptLytaclA3UTBDUkpQT2JVQWl6aWllQTRZbm9HTUpuWjR3VzNMeG1USEpvVjE5SVltYTJ2eitaS3hrSHVLWkkKc3lkUmcwOEhleFBHallvcGc2aG04akZUYTl3SktSKzZtQ3hTZGt5ZjVkdDhGNVl4RkRFU25QSDUxc2IzaGdibgpLR0hVZ3pDQnZwSEI5ZUY4VTJNNmpUM0ZLSEtjUGU0K1ZEdmpCOG9CendLQmdRRHZuK2JxUEdBWG5KM1BmTDI5CmlGaDlBS1JnRlFNRUlpTm9aa1JsY09SUzJvc1RoRzFQS2RNeW96TzNKUDh2THE1QnlzOSt0VnZmS2tiN0JUaTAKQVJDekhLSGVnclFhREQ2UUJOcWtzUEM2ZFc0NWtsMlIxem5XM0dVNzl2dTExUE5zYVJSZ0JlNjBlTm5TSmVTdApIMU13Rkx4aTMwS1J5QkJhWnptZ1JLU2VMd0tCZ1FEcTdkbVV0VWZEcFY3OEJmQVlzdUNtREZpc1lJVGF1VzZYClVkRnVPdllxRjRydGRKMWV2VG5NaHRVbkJKTStRSmZsMnRMTWZKRXA0ZDNKV1VHMjI4UmlZZUp1dVgrWjdHSXYKMVd3YnFVRDZuZy93VmZGbFY1WXRKTHBIZG5JSkZXYWllTThidmlXMHoyek4xTWtnS2d0d0w4S3loQlFXYUtJbgpjSmRyUTd0Q093S0JnQURxQVQxL2dYWlZtSnlFQTAxSHlkNmdOQUJSMURNZDFqaTl1eUVQN3k4SnVtSVdyVHdTCkVzWXNyVFBUcGsyTnhnaG1ONmhxRkxHalBhWVRmUVhpd3llTHdtcFE0Vk1BSFBUN3I4SFZFdllESUtxRGptdlMKQUZ4N2RyOWx6OHYveGZYeDZLdjlHYzRDY0FKSE5yb2FWbnptZDFtQk5JWE4xNUlndHEyUDFYanRBb0dBWmV4VgpOcGhEajFVaTFYSjZEUzBtRzhSRmdGdkxwOTFGWnE4ZmpwUlVFa1R1aUVETXVicWM1ZWdsZCswYk9LbnJmTlNvCkdnRjlOVStCMm9ZMzVXNkpVQ21waEdKRVF2SjBVczVrUGNmN29mK0xhTGpRcHlnTnhuNGx0elZqR2gvSHpIdGYKVjJqeWtQUmcveGZ2UGw0ZllrZkdUNDdQN0R6dkJPOXJNaVZMaTlzQ2dZQWR6dGdBVXU1ZHljcFZ2REpiT2V6NAp5UVgyamdnWnRNRnJKUE5kVkZCY1N5SzhJaGhFdzQ0ZUg1VkJsOHRWaS9KMHdWUHVPR1BxOUNkclM5emFFYkxCCi9hU2NjcG8xOTRHWjIvSVFrVlN1QVhlOVY5bENWdmtCdUg5VklzZG1hWHUwMUxZT1Ara3VsZ1VzMzNNejBOMGsKemZ2TzNrN3lDVmZMcEVVZDFtYnpBZz09Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K

---
apiVersion: network.upcloud.m.crossplane.io/v1alpha1
kind: LoadBalancerFrontend
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1alpha1/loadbalancerfrontendtlsconfig
  labels:
    testing.upbound.io/example-name: lbfetls-example-frontend
  name: lbfetls-example-frontend
  namespace: crossplane-system
spec:
  forProvider:
    loadbalancerRef:
      name: lbfetls-example-lb
    defaultBackendNameRef:
      name: lbfetls-example-backend
    mode: http
    port: 8080
    networks:
      - name: public
  providerConfigRef:
    kind: ClusterProviderConfig
    name: default

---
apiVersion: network.upcloud.m.crossplane.io/v1alpha1
kind: LoadBalancerBackend
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1alpha1/loadbalancerfrontendtlsconfig
  labels:
    testing.upbound.io/example-name: lbfetls-example-backend
  name: lbfetls-example-backend
  namespace: crossplane-system
spec:
  forProvider:
    loadbalancerRef:
      name: lbfetls-example-lb
  providerConfigRef:
    kind: ClusterProviderConfig
    name: default

---
apiVersion: network.upcloud.m.crossplane.io/v1alpha1
kind: LoadBalancer
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1alpha1/loadbalancerfrontendtlsconfig
  labels:
    testing.upbound.io/example-name: lbfetls-example-lb
  name: lbfetls-example-lb
  namespace: crossplane-system
spec:
  forProvider:
    name: lbfetls-example-lb
    zone: fi-hel2
    plan: development
    configuredStatus: started
    networks:
      - name: private
        type: private
        family: IPv4
        networkRef:
          name: lbfetls-example-network
      - name: public
        type: public
        family: IPv4
  providerConfigRef:
    kind: ClusterProviderConfig
    name: default

---
apiVersion: network.upcloud.m.crossplane.io/v1alpha1
kind: Network
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1alpha1/loadbalancerfrontendtlsconfig
  labels:
    testing.upbound.io/example-name: lbfetls-example-network
  name: lbfetls-example-network
  namespace: crossplane-system
spec:
  forProvider:
    name: lbfetls-example-network
    zone: fi-hel2
    ipNetwork:
      address: 10.38.0.0/24
      dhcp: true
      family: IPv4
  providerConfigRef:
    kind: ClusterProviderConfig
    name: default
