apiVersion: server.upcloud.m.crossplane.io/v1alpha1
kind: FirewallRules
metadata:
  annotations:
    meta.upbound.io/example-id: server/v1alpha1/firewallrules
  labels:
    testing.upbound.io/example-name: firewallrules-example
  name: firewallrules-example
  namespace: crossplane-system
spec:
  forProvider:
    serverIdRef:
      name: firewallrules-example-server
    firewallRule:
      - action: accept
        direction: in
        family: IPv4
        protocol: tcp
        sourceAddressStart: 192.168.1.1
        sourceAddressEnd: 192.168.1.255
        destinationPortStart: '22'
        destinationPortEnd: '22'
        comment: Allow SSH from this network
  providerConfigRef:
    kind: ClusterProviderConfig
    name: default

---
apiVersion: server.upcloud.m.crossplane.io/v1alpha1
kind: Server
metadata:
  annotations:
    meta.upbound.io/example-id: server/v1alpha1/firewallrules
  labels:
    testing.upbound.io/example-name: firewallrules-example-server
  name: firewallrules-example-server
  namespace: crossplane-system
spec:
  forProvider:
    hostname: firewallrules-example-server
    title: firewallrules-example-server
    plan: 1xCPU-1GB
    zone: de-fra1
    metadata: true
    firewall: true
    labels:
      env: dev
      production: 'false'
    login:
      - user: example
    networkInterface:
      - type: public
      - type: private
        networkRef:
          name: firewallrules-example-network
    template:
      - size: 25
        storage: Ubuntu Server 24.04 LTS (Noble Numbat)
    storageDevices:
      - storageRef:
          name: firewallrules-example-storage
  providerConfigRef:
    kind: ClusterProviderConfig
    name: default

---
apiVersion: network.upcloud.m.crossplane.io/v1alpha1
kind: Network
metadata:
  annotations:
    meta.upbound.io/example-id: server/v1alpha1/firewallrules
  labels:
    testing.upbound.io/example-name: firewallrules-example-network
  name: firewallrules-example-network
  namespace: crossplane-system
spec:
  forProvider:
    name: firewallrules-example-network
    zone: de-fra1
    ipNetwork:
      - address: 10.12.0.0/24
        dhcp: true
        family: IPv4
  providerConfigRef:
    kind: ClusterProviderConfig
    name: default

---
apiVersion: storage.upcloud.m.crossplane.io/v1alpha1
kind: Storage
metadata:
  annotations:
    meta.upbound.io/example-id: server/v1alpha1/firewallrules
  labels:
    testing.upbound.io/example-name: firewallrules-example-storage
  name: firewallrules-example-storage
  namespace: crossplane-system
spec:
  forProvider:
    size: 10
    tier: standard
    title: firewallrules-example-storage
    zone: de-fra1
  providerConfigRef:
    kind: ClusterProviderConfig
    name: default
