apiVersion: server.upcloud.m.crossplane.io/v1alpha1
kind: ServerGroup
metadata:
  annotations:
    meta.upbound.io/example-id: server/v1alpha1/servergroup
  labels:
    testing.upbound.io/example-name: servergroup-example
  name: servergroup-example
  namespace: crossplane-system
spec:
  forProvider:
    title: servergroup-example
    antiAffinityPolicy: 'yes'
    labels:
      env: dev
    membersRefs:
      - name: servergroup-example-server
  providerConfigRef:
    kind: ClusterProviderConfig
    name: default

---
apiVersion: server.upcloud.m.crossplane.io/v1alpha1
kind: Server
metadata:
  annotations:
    meta.upbound.io/example-id: server/v1alpha1/servergroup
  labels:
    testing.upbound.io/example-name: servergroup-example-server
  name: servergroup-example-server
  namespace: crossplane-system
spec:
  forProvider:
    hostname: servergroup-example-server
    title: servergroup-example-server
    plan: 1xCPU-1GB
    zone: fi-hel2
    metadata: true
    firewall: true
    labels:
      env: dev
      production: 'false'
    login:
      user: example
    networkInterface:
      - type: public
      - type: private
        networkRef:
          name: servergroup-example-network
    template:
      size: 25
      storage: Ubuntu Server 24.04 LTS (Noble Numbat)
    storageDevices:
      - storageRef:
          name: servergroup-example-storage
  providerConfigRef:
    kind: ClusterProviderConfig
    name: default

---
apiVersion: network.upcloud.m.crossplane.io/v1alpha1
kind: Network
metadata:
  annotations:
    meta.upbound.io/example-id: server/v1alpha1/servergroup
  labels:
    testing.upbound.io/example-name: servergroup-example-network
  name: servergroup-example-network
  namespace: crossplane-system
spec:
  forProvider:
    name: servergroup-example-network
    zone: fi-hel2
    ipNetwork:
      address: 10.13.0.0/24
      dhcp: true
      family: IPv4
  providerConfigRef:
    kind: ClusterProviderConfig
    name: default

---
apiVersion: storage.upcloud.m.crossplane.io/v1alpha1
kind: Storage
metadata:
  annotations:
    meta.upbound.io/example-id: server/v1alpha1/servergroup
  labels:
    testing.upbound.io/example-name: servergroup-example-storage
  name: servergroup-example-storage
  namespace: crossplane-system
spec:
  forProvider:
    size: 10
    tier: standard
    title: servergroup-example-storage
    zone: fi-hel2
  providerConfigRef:
    kind: ClusterProviderConfig
    name: default
