apiVersion: server.upcloud.m.crossplane.io/v1alpha1
kind: Tag
metadata:
  annotations:
    meta.upbound.io/example-id: server/v1alpha1/tag
  labels:
    testing.upbound.io/example-name: tag-example
  name: tag-example
  namespace: crossplane-system
spec:
  forProvider:
    description: example tag
    serversRefs:
      - name: tag-example-server
  providerConfigRef:
    kind: ClusterProviderConfig
    name: default

---
apiVersion: server.upcloud.m.crossplane.io/v1alpha1
kind: Server
metadata:
  annotations:
    meta.upbound.io/example-id: server/v1alpha1/tag
  labels:
    testing.upbound.io/example-name: tag-example-server
  name: tag-example-server
  namespace: crossplane-system
spec:
  forProvider:
    hostname: tag-example-server
    title: tag-example-server
    plan: 1xCPU-1GB
    zone: fi-hel2
    metadata: true
    login:
      user: example
    networkInterface:
      - type: public
    template:
      size: 25
      storage: Ubuntu Server 24.04 LTS (Noble Numbat)
  providerConfigRef:
    kind: ClusterProviderConfig
    name: default
