// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

// Package namespaced contains Kubernetes API for the provider.
package namespaced

import (
	"k8s.io/apimachinery/pkg/runtime"

	v1alpha1 "github.com/crossplane-contrib/provider-upcloud/apis/namespaced/database/v1alpha1"
	v1alpha1network "github.com/crossplane-contrib/provider-upcloud/apis/namespaced/network/v1alpha1"
	v1alpha1objectstorage "github.com/crossplane-contrib/provider-upcloud/apis/namespaced/objectstorage/v1alpha1"
	v1alpha1server "github.com/crossplane-contrib/provider-upcloud/apis/namespaced/server/v1alpha1"
	v1alpha1storage "github.com/crossplane-contrib/provider-upcloud/apis/namespaced/storage/v1alpha1"
	v1alpha1uks "github.com/crossplane-contrib/provider-upcloud/apis/namespaced/uks/v1alpha1"
	v1alpha1namespaced "github.com/crossplane-contrib/provider-upcloud/apis/namespaced/v1alpha1"
	v1beta1 "github.com/crossplane-contrib/provider-upcloud/apis/namespaced/v1beta1"
)

func init() {
	// Register the types with the Scheme so the components can map objects to GroupVersionKinds and back
	AddToSchemes = append(AddToSchemes,
		v1alpha1.SchemeBuilder.AddToScheme,
		v1alpha1network.SchemeBuilder.AddToScheme,
		v1alpha1objectstorage.SchemeBuilder.AddToScheme,
		v1alpha1server.SchemeBuilder.AddToScheme,
		v1alpha1storage.SchemeBuilder.AddToScheme,
		v1alpha1uks.SchemeBuilder.AddToScheme,
		v1alpha1namespaced.SchemeBuilder.AddToScheme,
		v1beta1.SchemeBuilder.AddToScheme,
	)
}

// AddToSchemes may be used to add all resources defined in the project to a Scheme
var AddToSchemes runtime.SchemeBuilder

// AddToScheme adds all Resources to the Scheme
func AddToScheme(s *runtime.Scheme) error {
	return AddToSchemes.AddToScheme(s)
}
