apiVersion: database.upcloud.m.crossplane.io/v1alpha1
kind: ManagedDatabasePostgresql
metadata:
  annotations:
    meta.upbound.io/example-id: database/v1alpha1/manageddatabasepostgresql
  labels:
    testing.upbound.io/example-name: postgresql-example
  name: postgresql-example
  namespace: crossplane-system
spec:
  forProvider:
    name: postgresql-example
    title: postgresql-example
    plan: 1x1xCPU-2GB-25GB
    zone: de-fra1
  providerConfigRef:
    kind: ClusterProviderConfig
    name: default
