apiVersion: database.upcloud.crossplane.io/v1alpha1
kind: ManagedDatabaseMysql
metadata:
  annotations:
    meta.upbound.io/example-id: database/v1alpha1/manageddatabasemysql
  labels:
    testing.upbound.io/example-name: mysql-example
  name: mysql-example
spec:
  forProvider:
    name: mysql-example
    title: mysql-example
    plan: 1x1xCPU-2GB-25GB
    zone: fi-hel1
  providerConfigRef:
    name: default
