apiVersion: database.upcloud.crossplane.io/v1alpha1
kind: ManagedDatabaseLogicalDatabase
metadata:
  annotations:
    meta.upbound.io/example-id: database/v1alpha1/manageddatabaselogicaldatabase
  labels:
    testing.upbound.io/example-name: logicaldb-example
  name: logicaldb-example
spec:
  forProvider:
    serviceRef:
      name: logicaldb-example-postgresql
  providerConfigRef:
    name: default

---
apiVersion: database.upcloud.crossplane.io/v1alpha1
kind: ManagedDatabasePostgresql
metadata:
  annotations:
    meta.upbound.io/example-id: database/v1alpha1/manageddatabaselogicaldatabase
  labels:
    testing.upbound.io/example-name: logicaldb-example-postgresql
  name: logicaldb-example-postgresql
spec:
  forProvider:
    name: logicaldb-example-postgresql
    title: logicaldb-example-postgresql
    plan: 1x1xCPU-2GB-25GB
    zone: de-fra1
  providerConfigRef:
    name: default
