apiVersion: database.upcloud.crossplane.io/v1alpha1
kind: ManagedDatabasePostgresql
metadata:
  annotations:
    meta.upbound.io/example-id: database/v1alpha1/manageddatabasepostgresql
  labels:
    testing.upbound.io/example-name: postgresql-example
  name: postgresql-example
spec:
  forProvider:
    name: postgresql-example
    title: postgresql-example
    plan: 1x1xCPU-2GB-25GB
    zone: fi-hel2
  providerConfigRef:
    name: default
