apiVersion: storage.upcloud.crossplane.io/v1alpha1
kind: Storage
metadata:
  name: example
spec:
  forProvider:
    size: 10
    tier: standard
    title: crossplane-example-additional-disk
    zone: de-fra1