apiVersion: network.upcloud.crossplane.io/v1alpha1
kind: LoadBalancerFrontend
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1alpha1/loadbalancerfrontend
  labels:
    testing.upbound.io/example-name: lb_fe_1
  name: lb-fe-1
spec:
  forProvider:
    defaultBackendNameSelector:
      matchLabels:
        testing.upbound.io/example-name: upcloud_loadbalancer_backend
    loadbalancerSelector:
      matchLabels:
        testing.upbound.io/example-name: upcloud_loadbalancer
    mode: http
    networks:
    - name: ${resource.upcloud_loadbalancer.lb.networks[1].name}
    port: 8080

---

apiVersion: network.upcloud.crossplane.io/v1alpha1
kind: LoadBalancer
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1alpha1/loadbalancerfrontend
  labels:
    testing.upbound.io/example-name: lb
  name: lb
spec:
  forProvider:
    configuredStatus: started
    name: lb-test
    networks:
    - family: IPv4
      name: Private-Net
      networkSelector:
        matchLabels:
          testing.upbound.io/example-name: upcloud_network
      type: private
    - family: IPv4
      name: Public-Net
      type: public
    plan: development
    zone: ${var.lb_zone}

---

apiVersion: network.upcloud.crossplane.io/v1alpha1
kind: LoadBalancerBackend
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1alpha1/loadbalancerfrontend
  labels:
    testing.upbound.io/example-name: lb_be_1
  name: lb-be-1
spec:
  forProvider:
    loadbalancerSelector:
      matchLabels:
        testing.upbound.io/example-name: upcloud_loadbalancer

---

apiVersion: network.upcloud.crossplane.io/v1alpha1
kind: Network
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1alpha1/loadbalancerfrontend
  labels:
    testing.upbound.io/example-name: lb_network
  name: lb-network
spec:
  forProvider:
    ipNetwork:
    - address: 10.0.0.0/24
      dhcp: true
      family: IPv4
    name: lb-test-net
    zone: ${var.lb_zone}
