apiVersion: network.upcloud.crossplane.io/v1alpha1
kind: LoadBalancerStaticBackendMember
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1alpha1/loadbalancerstaticbackendmember
  labels:
    testing.upbound.io/example-name: lb_be_1_sm_1
  name: lb-be-1-sm-1
spec:
  forProvider:
    backendSelector:
      matchLabels:
        testing.upbound.io/example-name: upcloud_loadbalancer_backend
    enabled: true
    ip: 10.0.0.10
    maxSessions: 0
    port: 8000
    weight: 10

---

apiVersion: network.upcloud.crossplane.io/v1alpha1
kind: LoadBalancer
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1alpha1/loadbalancerstaticbackendmember
  labels:
    testing.upbound.io/example-name: lb
  name: lb
spec:
  forProvider:
    configuredStatus: started
    name: lb-test
    networkSelector:
      matchLabels:
        testing.upbound.io/example-name: upcloud_network
    plan: development
    zone: ${var.lb_zone}

---

apiVersion: network.upcloud.crossplane.io/v1alpha1
kind: LoadBalancerBackend
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1alpha1/loadbalancerstaticbackendmember
  labels:
    testing.upbound.io/example-name: lb_be_1
  name: lb-be-1
spec:
  forProvider:
    loadbalancerSelector:
      matchLabels:
        testing.upbound.io/example-name: upcloud_loadbalancer

---

apiVersion: network.upcloud.crossplane.io/v1alpha1
kind: Network
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1alpha1/loadbalancerstaticbackendmember
  labels:
    testing.upbound.io/example-name: lb_network
  name: lb-network
spec:
  forProvider:
    ipNetwork:
    - address: 10.0.0.0/24
      dhcp: true
      family: IPv4
    name: lb-test-net
    zone: ${var.lb_zone}
