// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type GatewayConnectionInitParameters struct {

	// (String) The ID of the upcloud_gateway resource to which the connection belongs.
	// The ID of the upcloud_gateway resource to which the connection belongs.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upcloud/apis/namespaced/network/v1alpha1.Gateway
	Gateway *string `json:"gateway,omitempty" tf:"gateway,omitempty"`

	// Reference to a Gateway in network to populate gateway.
	// +kubebuilder:validation:Optional
	GatewayRef *v2.NamespacedReference `json:"gatewayRef,omitempty" tf:"-"`

	// Selector for a Gateway in network to populate gateway.
	// +kubebuilder:validation:Optional
	GatewaySelector *v2.NamespacedSelector `json:"gatewaySelector,omitempty" tf:"-"`

	// (Block Set) Route for the UpCloud side of the network. (see below for nested schema)
	// Route for the UpCloud side of the network.
	LocalRoute []LocalRouteInitParameters `json:"localRoute,omitempty" tf:"local_route,omitempty"`

	// (String) The name of the connection, should be unique within the gateway.
	// The name of the connection, should be unique within the gateway.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Block Set) Route for the remote side of the network. (see below for nested schema)
	// Route for the remote side of the network.
	RemoteRoute []RemoteRouteInitParameters `json:"remoteRoute,omitempty" tf:"remote_route,omitempty"`

	// (String) The type of the connection; currently the only supported type is 'ipsec'.
	// The type of the connection; currently the only supported type is 'ipsec'.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type GatewayConnectionObservation struct {

	// (String) The ID of the upcloud_gateway resource to which the connection belongs.
	// The ID of the upcloud_gateway resource to which the connection belongs.
	Gateway *string `json:"gateway,omitempty" tf:"gateway,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Block Set) Route for the UpCloud side of the network. (see below for nested schema)
	// Route for the UpCloud side of the network.
	LocalRoute []LocalRouteObservation `json:"localRoute,omitempty" tf:"local_route,omitempty"`

	// (String) The name of the connection, should be unique within the gateway.
	// The name of the connection, should be unique within the gateway.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Block Set) Route for the remote side of the network. (see below for nested schema)
	// Route for the remote side of the network.
	RemoteRoute []RemoteRouteObservation `json:"remoteRoute,omitempty" tf:"remote_route,omitempty"`

	// (List of String) List of connection's tunnels names. Note that this field can have outdated information as connections are created by a separate resource. To make sure that you have the most recent data run 'terrafrom refresh'.
	// List of connection's tunnels names. Note that this field can have outdated information as connections are created by a separate resource. To make sure that you have the most recent data run 'terrafrom refresh'.
	Tunnels []*string `json:"tunnels,omitempty" tf:"tunnels,omitempty"`

	// (String) The type of the connection; currently the only supported type is 'ipsec'.
	// The type of the connection; currently the only supported type is 'ipsec'.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String) The UUID of the connection
	// The UUID of the connection
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`
}

type GatewayConnectionParameters struct {

	// (String) The ID of the upcloud_gateway resource to which the connection belongs.
	// The ID of the upcloud_gateway resource to which the connection belongs.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upcloud/apis/namespaced/network/v1alpha1.Gateway
	// +kubebuilder:validation:Optional
	Gateway *string `json:"gateway,omitempty" tf:"gateway,omitempty"`

	// Reference to a Gateway in network to populate gateway.
	// +kubebuilder:validation:Optional
	GatewayRef *v2.NamespacedReference `json:"gatewayRef,omitempty" tf:"-"`

	// Selector for a Gateway in network to populate gateway.
	// +kubebuilder:validation:Optional
	GatewaySelector *v2.NamespacedSelector `json:"gatewaySelector,omitempty" tf:"-"`

	// (Block Set) Route for the UpCloud side of the network. (see below for nested schema)
	// Route for the UpCloud side of the network.
	// +kubebuilder:validation:Optional
	LocalRoute []LocalRouteParameters `json:"localRoute,omitempty" tf:"local_route,omitempty"`

	// (String) The name of the connection, should be unique within the gateway.
	// The name of the connection, should be unique within the gateway.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Block Set) Route for the remote side of the network. (see below for nested schema)
	// Route for the remote side of the network.
	// +kubebuilder:validation:Optional
	RemoteRoute []RemoteRouteParameters `json:"remoteRoute,omitempty" tf:"remote_route,omitempty"`

	// (String) The type of the connection; currently the only supported type is 'ipsec'.
	// The type of the connection; currently the only supported type is 'ipsec'.
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type LocalRouteInitParameters struct {

	// (String) The name of the connection, should be unique within the gateway.
	// Name of the route
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Destination prefix of the route; needs to be a valid IPv4 prefix
	// Destination prefix of the route; needs to be a valid IPv4 prefix
	StaticNetwork *string `json:"staticNetwork,omitempty" tf:"static_network,omitempty"`

	// (String) The type of the connection; currently the only supported type is 'ipsec'.
	// Type of route; currently the only supported type is 'static'
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type LocalRouteObservation struct {

	// (String) The name of the connection, should be unique within the gateway.
	// Name of the route
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Destination prefix of the route; needs to be a valid IPv4 prefix
	// Destination prefix of the route; needs to be a valid IPv4 prefix
	StaticNetwork *string `json:"staticNetwork,omitempty" tf:"static_network,omitempty"`

	// (String) The type of the connection; currently the only supported type is 'ipsec'.
	// Type of route; currently the only supported type is 'static'
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type LocalRouteParameters struct {

	// (String) The name of the connection, should be unique within the gateway.
	// Name of the route
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`

	// (String) Destination prefix of the route; needs to be a valid IPv4 prefix
	// Destination prefix of the route; needs to be a valid IPv4 prefix
	// +kubebuilder:validation:Optional
	StaticNetwork *string `json:"staticNetwork" tf:"static_network,omitempty"`

	// (String) The type of the connection; currently the only supported type is 'ipsec'.
	// Type of route; currently the only supported type is 'static'
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type RemoteRouteInitParameters struct {

	// (String) The name of the connection, should be unique within the gateway.
	// Name of the route
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Destination prefix of the route; needs to be a valid IPv4 prefix
	// Destination prefix of the route; needs to be a valid IPv4 prefix
	StaticNetwork *string `json:"staticNetwork,omitempty" tf:"static_network,omitempty"`

	// (String) The type of the connection; currently the only supported type is 'ipsec'.
	// Type of route; currently the only supported type is 'static'
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type RemoteRouteObservation struct {

	// (String) The name of the connection, should be unique within the gateway.
	// Name of the route
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Destination prefix of the route; needs to be a valid IPv4 prefix
	// Destination prefix of the route; needs to be a valid IPv4 prefix
	StaticNetwork *string `json:"staticNetwork,omitempty" tf:"static_network,omitempty"`

	// (String) The type of the connection; currently the only supported type is 'ipsec'.
	// Type of route; currently the only supported type is 'static'
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type RemoteRouteParameters struct {

	// (String) The name of the connection, should be unique within the gateway.
	// Name of the route
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`

	// (String) Destination prefix of the route; needs to be a valid IPv4 prefix
	// Destination prefix of the route; needs to be a valid IPv4 prefix
	// +kubebuilder:validation:Optional
	StaticNetwork *string `json:"staticNetwork" tf:"static_network,omitempty"`

	// (String) The type of the connection; currently the only supported type is 'ipsec'.
	// Type of route; currently the only supported type is 'static'
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

// GatewayConnectionSpec defines the desired state of GatewayConnection
type GatewayConnectionSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            GatewayConnectionParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider GatewayConnectionInitParameters `json:"initProvider,omitempty"`
}

// GatewayConnectionStatus defines the observed state of GatewayConnection.
type GatewayConnectionStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               GatewayConnectionObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// GatewayConnection is the Schema for the GatewayConnections API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,upcloud}
type GatewayConnection struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   GatewayConnectionSpec   `json:"spec"`
	Status GatewayConnectionStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// GatewayConnectionList contains a list of GatewayConnections
type GatewayConnectionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []GatewayConnection `json:"items"`
}

// Repository type metadata.
var (
	GatewayConnection_Kind             = "GatewayConnection"
	GatewayConnection_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: GatewayConnection_Kind}.String()
	GatewayConnection_KindAPIVersion   = GatewayConnection_Kind + "." + CRDGroupVersion.String()
	GatewayConnection_GroupVersionKind = CRDGroupVersion.WithKind(GatewayConnection_Kind)
)

func init() {
	SchemeBuilder.Register(&GatewayConnection{}, &GatewayConnectionList{})
}
