apiVersion: objectstorage.upcloud.m.crossplane.io/v1alpha1
kind: ManagedObjectStorageCustomDomain
metadata:
  annotations:
    meta.upbound.io/example-id: objectstorage/v1alpha1/managedobjectstoragecustomdomain
  labels:
    testing.upbound.io/example-name: this
  name: this
  namespace: upbound-system
spec:
  forProvider:
    serviceUuidSelector:
      matchLabels:
        testing.upbound.io/example-name: this

---

apiVersion: objectstorage.upcloud.m.crossplane.io/v1alpha1
kind: ManagedObjectStorage
metadata:
  annotations:
    meta.upbound.io/example-id: objectstorage/v1alpha1/managedobjectstoragecustomdomain
  labels:
    testing.upbound.io/example-name: this
  name: this
  namespace: upbound-system
spec:
  forProvider:
    configuredStatus: started
    name: object-storage-custom-domain-example
    network:
    - family: IPv4
      name: public
      type: public
    region: europe-1
