apiVersion: network.upcloud.m.crossplane.io/v1alpha1
kind: LoadBalancerFrontendRule
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1alpha1/loadbalancerfrontendrule
  labels:
    testing.upbound.io/example-name: lb_fe_1_r1
  name: lb-fe-1-r1
  namespace: upbound-system
spec:
  forProvider:
    actions:
    - httpRewritePath:
      - matchPattern: ^/old/(.*)$
        rewriteTo: /new/\1
      useBackend:
      - backendNameSelector:
          matchLabels:
            testing.upbound.io/example-name: upcloud_loadbalancer_backend
    frontendSelector:
      matchLabels:
        testing.upbound.io/example-name: upcloud_loadbalancer_frontend
    matchers:
    - srcIp:
      - value: 192.168.0.0/24
    priority: 10

---

apiVersion: network.upcloud.m.crossplane.io/v1alpha1
kind: LoadBalancer
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1alpha1/loadbalancerfrontendrule
  labels:
    testing.upbound.io/example-name: lb
  name: lb
  namespace: upbound-system
spec:
  forProvider:
    configuredStatus: started
    name: lb-test
    networks:
    - family: IPv4
      name: public
      type: public
    - family: IPv4
      name: private
      networkSelector:
        matchLabels:
          testing.upbound.io/example-name: upcloud_network
      type: private
    plan: development
    zone: ${var.lb_zone}

---

apiVersion: network.upcloud.m.crossplane.io/v1alpha1
kind: LoadBalancerBackend
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1alpha1/loadbalancerfrontendrule
  labels:
    testing.upbound.io/example-name: lb_be_1
  name: lb-be-1
  namespace: upbound-system
spec:
  forProvider:
    loadbalancerSelector:
      matchLabels:
        testing.upbound.io/example-name: upcloud_loadbalancer

---

apiVersion: network.upcloud.m.crossplane.io/v1alpha1
kind: LoadBalancerFrontend
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1alpha1/loadbalancerfrontendrule
  labels:
    testing.upbound.io/example-name: lb_fe_1
  name: lb-fe-1
  namespace: upbound-system
spec:
  forProvider:
    defaultBackendNameSelector:
      matchLabels:
        testing.upbound.io/example-name: upcloud_loadbalancer_backend
    loadbalancerSelector:
      matchLabels:
        testing.upbound.io/example-name: upcloud_loadbalancer
    mode: http
    port: 8080

---

apiVersion: network.upcloud.m.crossplane.io/v1alpha1
kind: Network
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1alpha1/loadbalancerfrontendrule
  labels:
    testing.upbound.io/example-name: lb_network
  name: lb-network
  namespace: upbound-system
spec:
  forProvider:
    ipNetwork:
    - address: 10.0.0.0/24
      dhcp: true
      family: IPv4
    name: lb-test-net
    zone: ${var.lb_zone}
