apiVersion: network.upcloud.m.crossplane.io/v1alpha1
kind: LoadBalancerResolver
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1alpha1/loadbalancerresolver
  labels:
    testing.upbound.io/example-name: lb_resolver_1
  name: lb-resolver-1
  namespace: upbound-system
spec:
  forProvider:
    cacheInvalid: 10
    cacheValid: 100
    loadbalancerSelector:
      matchLabels:
        testing.upbound.io/example-name: upcloud_loadbalancer
    nameservers:
    - 10.0.0.10:53
    retries: 5
    timeout: 10
    timeoutRetry: 10

---

apiVersion: network.upcloud.m.crossplane.io/v1alpha1
kind: LoadBalancer
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1alpha1/loadbalancerresolver
  labels:
    testing.upbound.io/example-name: lb
  name: lb
  namespace: upbound-system
spec:
  forProvider:
    configuredStatus: started
    name: lb-test
    networkSelector:
      matchLabels:
        testing.upbound.io/example-name: upcloud_network
    plan: development
    zone: ${var.lb_zone}

---

apiVersion: network.upcloud.m.crossplane.io/v1alpha1
kind: Network
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1alpha1/loadbalancerresolver
  labels:
    testing.upbound.io/example-name: lb_network
  name: lb-network
  namespace: upbound-system
spec:
  forProvider:
    ipNetwork:
    - address: 10.0.0.0/24
      dhcp: true
      family: IPv4
    name: lb-test-net
    zone: ${var.lb_zone}
