// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type FirewallRulesetInitParameters struct {

	// (Boolean) Whether default DNS rules are enabled.
	// Whether default DNS rules are enabled.
	DefaultDNSRulesEnabled *bool `json:"defaultDnsRulesEnabled,omitempty" tf:"default_dns_rules_enabled,omitempty"`

	// (String) Description of the firewall ruleset.
	// Description of the firewall ruleset.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Boolean) Whether the ruleset is enabled.
	// Whether the ruleset is enabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Map of String) Ruleset labels as key/value pairs.
	// Ruleset labels as key/value pairs.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String) Name of the firewall ruleset.
	// Name of the firewall ruleset.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// based index assigned by the API and cannot be configured. (see below for nested schema)
	Rules []RulesInitParameters `json:"rules,omitempty" tf:"rules,omitempty"`
}

type FirewallRulesetObservation struct {

	// (String) Creation timestamp.
	// Creation timestamp.
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// (Boolean) Whether default DNS rules are enabled.
	// Whether default DNS rules are enabled.
	DefaultDNSRulesEnabled *bool `json:"defaultDnsRulesEnabled,omitempty" tf:"default_dns_rules_enabled,omitempty"`

	// (String) Description of the firewall ruleset.
	// Description of the firewall ruleset.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Boolean) Whether the ruleset is enabled.
	// Whether the ruleset is enabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) Firewall ruleset UUID.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Map of String) Ruleset labels as key/value pairs.
	// Ruleset labels as key/value pairs.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String) Name of the firewall ruleset.
	// Name of the firewall ruleset.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// based index assigned by the API and cannot be configured. (see below for nested schema)
	Rules []RulesObservation `json:"rules,omitempty" tf:"rules,omitempty"`

	// (String) Last update timestamp.
	// Last update timestamp.
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`

	// (Number) Ruleset version.
	// Ruleset version.
	Version *float64 `json:"version,omitempty" tf:"version,omitempty"`
}

type FirewallRulesetParameters struct {

	// (Boolean) Whether default DNS rules are enabled.
	// Whether default DNS rules are enabled.
	// +kubebuilder:validation:Optional
	DefaultDNSRulesEnabled *bool `json:"defaultDnsRulesEnabled,omitempty" tf:"default_dns_rules_enabled,omitempty"`

	// (String) Description of the firewall ruleset.
	// Description of the firewall ruleset.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Boolean) Whether the ruleset is enabled.
	// Whether the ruleset is enabled.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Map of String) Ruleset labels as key/value pairs.
	// Ruleset labels as key/value pairs.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String) Name of the firewall ruleset.
	// Name of the firewall ruleset.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// based index assigned by the API and cannot be configured. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Rules []RulesParameters `json:"rules,omitempty" tf:"rules,omitempty"`
}

type RulesInitParameters struct {

	// (String) Rule action.
	// Rule action.
	Action *string `json:"action,omitempty" tf:"action,omitempty"`

	// (String) Rule comment.
	// Rule comment.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (String) Destination CIDR block.
	// Destination CIDR block.
	DestinationAddressCidr *string `json:"destinationAddressCidr,omitempty" tf:"destination_address_cidr,omitempty"`

	// (String) End of destination IP address range.
	// End of destination IP address range.
	DestinationAddressEnd *string `json:"destinationAddressEnd,omitempty" tf:"destination_address_end,omitempty"`

	// (String) Start of destination IP address range.
	// Start of destination IP address range.
	DestinationAddressStart *string `json:"destinationAddressStart,omitempty" tf:"destination_address_start,omitempty"`

	// (Number) End of destination port range.
	// End of destination port range.
	DestinationPortEnd *float64 `json:"destinationPortEnd,omitempty" tf:"destination_port_end,omitempty"`

	// (Number) Start of destination port range.
	// Start of destination port range.
	DestinationPortStart *float64 `json:"destinationPortStart,omitempty" tf:"destination_port_start,omitempty"`

	// (String) Traffic direction the rule applies to.
	// Traffic direction the rule applies to.
	Direction *string `json:"direction,omitempty" tf:"direction,omitempty"`

	// (Boolean) Whether the ruleset is enabled.
	// Whether the rule is enabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) Address family.
	// Address family.
	Family *string `json:"family,omitempty" tf:"family,omitempty"`

	// (Number) ICMP type number.
	// ICMP type number.
	IcmpType *float64 `json:"icmpType,omitempty" tf:"icmp_type,omitempty"`

	// (String) IP protocol.
	// IP protocol.
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`

	// (String) Source CIDR block.
	// Source CIDR block.
	SourceAddressCidr *string `json:"sourceAddressCidr,omitempty" tf:"source_address_cidr,omitempty"`

	// (String) End of source IP address range.
	// End of source IP address range.
	SourceAddressEnd *string `json:"sourceAddressEnd,omitempty" tf:"source_address_end,omitempty"`

	// (String) Start of source IP address range.
	// Start of source IP address range.
	SourceAddressStart *string `json:"sourceAddressStart,omitempty" tf:"source_address_start,omitempty"`

	// (Number) End of source port range.
	// End of source port range.
	SourcePortEnd *float64 `json:"sourcePortEnd,omitempty" tf:"source_port_end,omitempty"`

	// (Number) Start of source port range.
	// Start of source port range.
	SourcePortStart *float64 `json:"sourcePortStart,omitempty" tf:"source_port_start,omitempty"`
}

type RulesObservation struct {

	// (String) Rule action.
	// Rule action.
	Action *string `json:"action,omitempty" tf:"action,omitempty"`

	// (String) Rule comment.
	// Rule comment.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (String) Destination CIDR block.
	// Destination CIDR block.
	DestinationAddressCidr *string `json:"destinationAddressCidr,omitempty" tf:"destination_address_cidr,omitempty"`

	// (String) End of destination IP address range.
	// End of destination IP address range.
	DestinationAddressEnd *string `json:"destinationAddressEnd,omitempty" tf:"destination_address_end,omitempty"`

	// (String) Start of destination IP address range.
	// Start of destination IP address range.
	DestinationAddressStart *string `json:"destinationAddressStart,omitempty" tf:"destination_address_start,omitempty"`

	// (Number) End of destination port range.
	// End of destination port range.
	DestinationPortEnd *float64 `json:"destinationPortEnd,omitempty" tf:"destination_port_end,omitempty"`

	// (Number) Start of destination port range.
	// Start of destination port range.
	DestinationPortStart *float64 `json:"destinationPortStart,omitempty" tf:"destination_port_start,omitempty"`

	// (String) Traffic direction the rule applies to.
	// Traffic direction the rule applies to.
	Direction *string `json:"direction,omitempty" tf:"direction,omitempty"`

	// (Boolean) Whether the ruleset is enabled.
	// Whether the rule is enabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) Address family.
	// Address family.
	Family *string `json:"family,omitempty" tf:"family,omitempty"`

	// (Number) ICMP type number.
	// ICMP type number.
	IcmpType *float64 `json:"icmpType,omitempty" tf:"icmp_type,omitempty"`

	// based). Computed from the rule's index in the list.
	// Rule position (1-based). Computed from the rule's index in the list.
	Position *float64 `json:"position,omitempty" tf:"position,omitempty"`

	// (String) IP protocol.
	// IP protocol.
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`

	// (String) Source CIDR block.
	// Source CIDR block.
	SourceAddressCidr *string `json:"sourceAddressCidr,omitempty" tf:"source_address_cidr,omitempty"`

	// (String) End of source IP address range.
	// End of source IP address range.
	SourceAddressEnd *string `json:"sourceAddressEnd,omitempty" tf:"source_address_end,omitempty"`

	// (String) Start of source IP address range.
	// Start of source IP address range.
	SourceAddressStart *string `json:"sourceAddressStart,omitempty" tf:"source_address_start,omitempty"`

	// (Number) End of source port range.
	// End of source port range.
	SourcePortEnd *float64 `json:"sourcePortEnd,omitempty" tf:"source_port_end,omitempty"`

	// (Number) Start of source port range.
	// Start of source port range.
	SourcePortStart *float64 `json:"sourcePortStart,omitempty" tf:"source_port_start,omitempty"`
}

type RulesParameters struct {

	// (String) Rule action.
	// Rule action.
	// +kubebuilder:validation:Optional
	Action *string `json:"action" tf:"action,omitempty"`

	// (String) Rule comment.
	// Rule comment.
	// +kubebuilder:validation:Optional
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (String) Destination CIDR block.
	// Destination CIDR block.
	// +kubebuilder:validation:Optional
	DestinationAddressCidr *string `json:"destinationAddressCidr,omitempty" tf:"destination_address_cidr,omitempty"`

	// (String) End of destination IP address range.
	// End of destination IP address range.
	// +kubebuilder:validation:Optional
	DestinationAddressEnd *string `json:"destinationAddressEnd,omitempty" tf:"destination_address_end,omitempty"`

	// (String) Start of destination IP address range.
	// Start of destination IP address range.
	// +kubebuilder:validation:Optional
	DestinationAddressStart *string `json:"destinationAddressStart,omitempty" tf:"destination_address_start,omitempty"`

	// (Number) End of destination port range.
	// End of destination port range.
	// +kubebuilder:validation:Optional
	DestinationPortEnd *float64 `json:"destinationPortEnd,omitempty" tf:"destination_port_end,omitempty"`

	// (Number) Start of destination port range.
	// Start of destination port range.
	// +kubebuilder:validation:Optional
	DestinationPortStart *float64 `json:"destinationPortStart,omitempty" tf:"destination_port_start,omitempty"`

	// (String) Traffic direction the rule applies to.
	// Traffic direction the rule applies to.
	// +kubebuilder:validation:Optional
	Direction *string `json:"direction" tf:"direction,omitempty"`

	// (Boolean) Whether the ruleset is enabled.
	// Whether the rule is enabled.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) Address family.
	// Address family.
	// +kubebuilder:validation:Optional
	Family *string `json:"family" tf:"family,omitempty"`

	// (Number) ICMP type number.
	// ICMP type number.
	// +kubebuilder:validation:Optional
	IcmpType *float64 `json:"icmpType,omitempty" tf:"icmp_type,omitempty"`

	// (String) IP protocol.
	// IP protocol.
	// +kubebuilder:validation:Optional
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`

	// (String) Source CIDR block.
	// Source CIDR block.
	// +kubebuilder:validation:Optional
	SourceAddressCidr *string `json:"sourceAddressCidr,omitempty" tf:"source_address_cidr,omitempty"`

	// (String) End of source IP address range.
	// End of source IP address range.
	// +kubebuilder:validation:Optional
	SourceAddressEnd *string `json:"sourceAddressEnd,omitempty" tf:"source_address_end,omitempty"`

	// (String) Start of source IP address range.
	// Start of source IP address range.
	// +kubebuilder:validation:Optional
	SourceAddressStart *string `json:"sourceAddressStart,omitempty" tf:"source_address_start,omitempty"`

	// (Number) End of source port range.
	// End of source port range.
	// +kubebuilder:validation:Optional
	SourcePortEnd *float64 `json:"sourcePortEnd,omitempty" tf:"source_port_end,omitempty"`

	// (Number) Start of source port range.
	// Start of source port range.
	// +kubebuilder:validation:Optional
	SourcePortStart *float64 `json:"sourcePortStart,omitempty" tf:"source_port_start,omitempty"`
}

// FirewallRulesetSpec defines the desired state of FirewallRuleset
type FirewallRulesetSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   FirewallRulesetParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider FirewallRulesetInitParameters `json:"initProvider,omitempty"`
}

// FirewallRulesetStatus defines the observed state of FirewallRuleset.
type FirewallRulesetStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               FirewallRulesetObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// FirewallRuleset is the Schema for the FirewallRulesets API. This resource represents an UpCloud SDN firewall ruleset. Rules are managed as an ordered list; their position in the API is determined by their order in the rules list.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,upcloud}
type FirewallRuleset struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   FirewallRulesetSpec   `json:"spec"`
	Status FirewallRulesetStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// FirewallRulesetList contains a list of FirewallRulesets
type FirewallRulesetList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []FirewallRuleset `json:"items"`
}

// Repository type metadata.
var (
	FirewallRuleset_Kind             = "FirewallRuleset"
	FirewallRuleset_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: FirewallRuleset_Kind}.String()
	FirewallRuleset_KindAPIVersion   = FirewallRuleset_Kind + "." + CRDGroupVersion.String()
	FirewallRuleset_GroupVersionKind = CRDGroupVersion.WithKind(FirewallRuleset_Kind)
)

func init() {
	SchemeBuilder.Register(&FirewallRuleset{}, &FirewallRulesetList{})
}
