// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type LoadBalancerFrontendTLSConfigInitParameters struct {

	// (String) Reference to certificate bundle ID.
	// Reference to certificate bundle ID.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upcloud/apis/cluster/network/v1alpha1.LoadBalancerManualCertificateBundle
	CertificateBundle *string `json:"certificateBundle,omitempty" tf:"certificate_bundle,omitempty"`

	// Reference to a LoadBalancerManualCertificateBundle in network to populate certificateBundle.
	// +kubebuilder:validation:Optional
	CertificateBundleRef *v2.Reference `json:"certificateBundleRef,omitempty" tf:"-"`

	// Selector for a LoadBalancerManualCertificateBundle in network to populate certificateBundle.
	// +kubebuilder:validation:Optional
	CertificateBundleSelector *v2.Selector `json:"certificateBundleSelector,omitempty" tf:"-"`
}

type LoadBalancerFrontendTLSConfigObservation struct {

	// (String) Reference to certificate bundle ID.
	// Reference to certificate bundle ID.
	CertificateBundle *string `json:"certificateBundle,omitempty" tf:"certificate_bundle,omitempty"`

	// (String) ID of the load balancer frontend to which the TLS config is connected.
	// ID of the load balancer frontend to which the TLS config is connected.
	Frontend *string `json:"frontend,omitempty" tf:"frontend,omitempty"`

	// (String) ID of the TLS config. ID is in {load balancer UUID}/{frontend name}/{TLS config name} format.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type LoadBalancerFrontendTLSConfigParameters struct {

	// (String) Reference to certificate bundle ID.
	// Reference to certificate bundle ID.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upcloud/apis/cluster/network/v1alpha1.LoadBalancerManualCertificateBundle
	// +kubebuilder:validation:Optional
	CertificateBundle *string `json:"certificateBundle,omitempty" tf:"certificate_bundle,omitempty"`

	// Reference to a LoadBalancerManualCertificateBundle in network to populate certificateBundle.
	// +kubebuilder:validation:Optional
	CertificateBundleRef *v2.Reference `json:"certificateBundleRef,omitempty" tf:"-"`

	// Selector for a LoadBalancerManualCertificateBundle in network to populate certificateBundle.
	// +kubebuilder:validation:Optional
	CertificateBundleSelector *v2.Selector `json:"certificateBundleSelector,omitempty" tf:"-"`

	// (String) ID of the load balancer frontend to which the TLS config is connected.
	// ID of the load balancer frontend to which the TLS config is connected.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upcloud/apis/cluster/network/v1alpha1.LoadBalancerFrontend
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("id",true)
	// +kubebuilder:validation:Optional
	Frontend *string `json:"frontend,omitempty" tf:"frontend,omitempty"`

	// Reference to a LoadBalancerFrontend in network to populate frontend.
	// +kubebuilder:validation:Optional
	FrontendRef *v2.Reference `json:"frontendRef,omitempty" tf:"-"`

	// Selector for a LoadBalancerFrontend in network to populate frontend.
	// +kubebuilder:validation:Optional
	FrontendSelector *v2.Selector `json:"frontendSelector,omitempty" tf:"-"`
}

// LoadBalancerFrontendTLSConfigSpec defines the desired state of LoadBalancerFrontendTLSConfig
type LoadBalancerFrontendTLSConfigSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   LoadBalancerFrontendTLSConfigParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider LoadBalancerFrontendTLSConfigInitParameters `json:"initProvider,omitempty"`
}

// LoadBalancerFrontendTLSConfigStatus defines the observed state of LoadBalancerFrontendTLSConfig.
type LoadBalancerFrontendTLSConfigStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               LoadBalancerFrontendTLSConfigObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// LoadBalancerFrontendTLSConfig is the Schema for the LoadBalancerFrontendTLSConfigs API. This resource represents frontend TLS config
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,upcloud}
type LoadBalancerFrontendTLSConfig struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              LoadBalancerFrontendTLSConfigSpec   `json:"spec"`
	Status            LoadBalancerFrontendTLSConfigStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// LoadBalancerFrontendTLSConfigList contains a list of LoadBalancerFrontendTLSConfigs
type LoadBalancerFrontendTLSConfigList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []LoadBalancerFrontendTLSConfig `json:"items"`
}

// Repository type metadata.
var (
	LoadBalancerFrontendTLSConfig_Kind             = "LoadBalancerFrontendTLSConfig"
	LoadBalancerFrontendTLSConfig_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: LoadBalancerFrontendTLSConfig_Kind}.String()
	LoadBalancerFrontendTLSConfig_KindAPIVersion   = LoadBalancerFrontendTLSConfig_Kind + "." + CRDGroupVersion.String()
	LoadBalancerFrontendTLSConfig_GroupVersionKind = CRDGroupVersion.WithKind(LoadBalancerFrontendTLSConfig_Kind)
)

func init() {
	SchemeBuilder.Register(&LoadBalancerFrontendTLSConfig{}, &LoadBalancerFrontendTLSConfigList{})
}
