// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type RouterInitParameters struct {

	// value pairs to classify the router.
	// User defined key-value pairs to classify the router.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String) Name of the router.
	// Name of the router.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Block Set) A collection of user managed static routes for this router. (see below for nested schema)
	// A collection of user managed static routes for this router.
	StaticRoute []StaticRouteInitParameters `json:"staticRoute,omitempty" tf:"static_route,omitempty"`
}

type RouterObservation struct {

	// (List of String) List of UUIDs representing networks attached to this router.
	// List of UUIDs representing networks attached to this router.
	AttachedNetworks []*string `json:"attachedNetworks,omitempty" tf:"attached_networks,omitempty"`

	// (String) UUID of the router.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// value pairs to classify the router.
	// User defined key-value pairs to classify the router.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String) Name of the router.
	// Name of the router.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Block Set) A collection of user managed static routes for this router. (see below for nested schema)
	// A collection of user managed static routes for this router.
	StaticRoute []StaticRouteObservation `json:"staticRoute,omitempty" tf:"static_route,omitempty"`

	// (Set of Object) A collection of static routes for this router. This set includes both user and service defined static routes. The objects in this set use the same schema as static_route blocks. (see below for nested schema)
	// A collection of static routes for this router. This set includes both user and service defined static routes. The objects in this set use the same schema as `static_route` blocks.
	StaticRoutes []StaticRoutesObservation `json:"staticRoutes,omitempty" tf:"static_routes,omitempty"`

	// (String) Type of the router
	// Type of the router
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type RouterParameters struct {

	// value pairs to classify the router.
	// User defined key-value pairs to classify the router.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String) Name of the router.
	// Name of the router.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Block Set) A collection of user managed static routes for this router. (see below for nested schema)
	// A collection of user managed static routes for this router.
	// +kubebuilder:validation:Optional
	StaticRoute []StaticRouteParameters `json:"staticRoute,omitempty" tf:"static_route,omitempty"`
}

type StaticRouteInitParameters struct {

	// (String) Name of the router.
	// Name or description of the route.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Next hop address. NOTE: For static route to be active the next hop has to be an address of a reachable running Cloud Server in one of the Private Networks attached to the router.
	// Next hop address. NOTE: For static route to be active the next hop has to be an address of a reachable running Cloud Server in one of the Private Networks attached to the router.
	Nexthop *string `json:"nexthop,omitempty" tf:"nexthop,omitempty"`

	// (String) Destination prefix of the route.
	// Destination prefix of the route.
	Route *string `json:"route,omitempty" tf:"route,omitempty"`
}

type StaticRouteObservation struct {

	// (String) Name of the router.
	// Name or description of the route.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Next hop address. NOTE: For static route to be active the next hop has to be an address of a reachable running Cloud Server in one of the Private Networks attached to the router.
	// Next hop address. NOTE: For static route to be active the next hop has to be an address of a reachable running Cloud Server in one of the Private Networks attached to the router.
	Nexthop *string `json:"nexthop,omitempty" tf:"nexthop,omitempty"`

	// (String) Destination prefix of the route.
	// Destination prefix of the route.
	Route *string `json:"route,omitempty" tf:"route,omitempty"`

	// (String) Type of the router
	// Type of the route.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type StaticRouteParameters struct {

	// (String) Name of the router.
	// Name or description of the route.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Next hop address. NOTE: For static route to be active the next hop has to be an address of a reachable running Cloud Server in one of the Private Networks attached to the router.
	// Next hop address. NOTE: For static route to be active the next hop has to be an address of a reachable running Cloud Server in one of the Private Networks attached to the router.
	// +kubebuilder:validation:Optional
	Nexthop *string `json:"nexthop" tf:"nexthop,omitempty"`

	// (String) Destination prefix of the route.
	// Destination prefix of the route.
	// +kubebuilder:validation:Optional
	Route *string `json:"route" tf:"route,omitempty"`
}

type StaticRoutesInitParameters struct {
}

type StaticRoutesObservation struct {

	// (String) Name of the router.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Next hop address. NOTE: For static route to be active the next hop has to be an address of a reachable running Cloud Server in one of the Private Networks attached to the router.
	Nexthop *string `json:"nexthop,omitempty" tf:"nexthop,omitempty"`

	// (String) Destination prefix of the route.
	Route *string `json:"route,omitempty" tf:"route,omitempty"`

	// (String) Type of the router
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type StaticRoutesParameters struct {
}

// RouterSpec defines the desired state of Router
type RouterSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   RouterParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider RouterInitParameters `json:"initProvider,omitempty"`
}

// RouterStatus defines the observed state of Router.
type RouterStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               RouterObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Router is the Schema for the Routers API. Routers can be used to connect multiple Private Networks. UpCloud Servers on any attached network can communicate directly with each other.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,upcloud}
type Router struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.labels) || (has(self.initProvider) && has(self.initProvider.labels))",message="spec.forProvider.labels is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.staticRoute) || (has(self.initProvider) && has(self.initProvider.staticRoute))",message="spec.forProvider.staticRoute is a required parameter"
	Spec   RouterSpec   `json:"spec"`
	Status RouterStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RouterList contains a list of Routers
type RouterList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Router `json:"items"`
}

// Repository type metadata.
var (
	Router_Kind             = "Router"
	Router_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Router_Kind}.String()
	Router_KindAPIVersion   = Router_Kind + "." + CRDGroupVersion.String()
	Router_GroupVersionKind = CRDGroupVersion.WithKind(Router_Kind)
)

func init() {
	SchemeBuilder.Register(&Router{}, &RouterList{})
}
