apiVersion: server.upcloud.crossplane.io/v1alpha1
kind: Server
metadata:
  annotations:
    meta.upbound.io/example-id: server/v1alpha1/server
  labels:
    testing.upbound.io/example-name: server-example
  name: server-example
spec:
  forProvider:
    hostname: server-example
    title: server-example
    plan: 1xCPU-1GB
    zone: fi-hel2
    metadata: true
    firewall: true
    labels:
      env: dev
      production: 'false'
    login:
      user: example
    networkInterface:
      - type: public
      - type: private
        networkRef:
          name: server-example-network
    template:
      size: 25
      storage: Ubuntu Server 24.04 LTS (Noble Numbat)
    storageDevices:
      - storageRef:
          name: server-example-storage
  providerConfigRef:
    name: default

---
apiVersion: network.upcloud.crossplane.io/v1alpha1
kind: Network
metadata:
  annotations:
    meta.upbound.io/example-id: server/v1alpha1/server
  labels:
    testing.upbound.io/example-name: server-example-network
  name: server-example-network
spec:
  forProvider:
    name: server-example-network
    zone: fi-hel2
    ipNetwork:
      address: 10.12.0.0/24
      dhcp: true
      family: IPv4
  providerConfigRef:
    name: default

---
apiVersion: storage.upcloud.crossplane.io/v1alpha1
kind: Storage
metadata:
  annotations:
    meta.upbound.io/example-id: server/v1alpha1/server
  labels:
    testing.upbound.io/example-name: server-example-storage
  name: server-example-storage
spec:
  forProvider:
    size: 10
    tier: standard
    title: server-example-storage
    zone: fi-hel2
  providerConfigRef:
    name: default
