// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type FileStorageShareInitParameters struct {

	// Absolute path exported by the share (e.g. `/public`).
	Path *string `json:"path,omitempty" tf:"path,omitempty"`
}

type FileStorageShareObservation struct {

	// UUID of the file storage service.
	FileStorage *string `json:"fileStorage,omitempty" tf:"file_storage,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Absolute path exported by the share (e.g. `/public`).
	Path *string `json:"path,omitempty" tf:"path,omitempty"`
}

type FileStorageShareParameters struct {

	// UUID of the file storage service.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upcloud/apis/namespaced/storage/v1alpha1.FileStorage
	// +kubebuilder:validation:Optional
	FileStorage *string `json:"fileStorage,omitempty" tf:"file_storage,omitempty"`

	// Reference to a FileStorage in storage to populate fileStorage.
	// +kubebuilder:validation:Optional
	FileStorageRef *v2.NamespacedReference `json:"fileStorageRef,omitempty" tf:"-"`

	// Selector for a FileStorage in storage to populate fileStorage.
	// +kubebuilder:validation:Optional
	FileStorageSelector *v2.NamespacedSelector `json:"fileStorageSelector,omitempty" tf:"-"`

	// Absolute path exported by the share (e.g. `/public`).
	// +kubebuilder:validation:Optional
	Path *string `json:"path,omitempty" tf:"path,omitempty"`
}

// FileStorageShareSpec defines the desired state of FileStorageShare
type FileStorageShareSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            FileStorageShareParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider FileStorageShareInitParameters `json:"initProvider,omitempty"`
}

// FileStorageShareStatus defines the observed state of FileStorageShare.
type FileStorageShareStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               FileStorageShareObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// FileStorageShare is the Schema for the FileStorageShares API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,upcloud}
type FileStorageShare struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.path) || (has(self.initProvider) && has(self.initProvider.path))",message="spec.forProvider.path is a required parameter"
	Spec   FileStorageShareSpec   `json:"spec"`
	Status FileStorageShareStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// FileStorageShareList contains a list of FileStorageShares
type FileStorageShareList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []FileStorageShare `json:"items"`
}

// Repository type metadata.
var (
	FileStorageShare_Kind             = "FileStorageShare"
	FileStorageShare_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: FileStorageShare_Kind}.String()
	FileStorageShare_KindAPIVersion   = FileStorageShare_Kind + "." + CRDGroupVersion.String()
	FileStorageShare_GroupVersionKind = CRDGroupVersion.WithKind(FileStorageShare_Kind)
)

func init() {
	SchemeBuilder.Register(&FileStorageShare{}, &FileStorageShareList{})
}
