// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0
// Code transformed by upjet. DO NOT EDIT.

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	common "github.com/crossplane-contrib/provider-upcloud/config/common"
	apisresolver "github.com/crossplane-contrib/provider-upcloud/internal/apis"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	xpresource "github.com/crossplane/crossplane-runtime/v2/pkg/resource"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

func (mg *FileStorage) ResolveReferences( // ResolveReferences of this FileStorage.
	ctx context.Context, c client.Reader) error {
	var m xpresource.Managed
	var l xpresource.ManagedList
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	if mg.Spec.ForProvider.Network != nil {
		{
			m, l, err = apisresolver.GetManagedResource("network.upcloud.m.crossplane.io", "v1alpha1", "Network", "NetworkList")
			if err != nil {
				return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
			}
			rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Network.UUID),
				Extract:      reference.ExternalName(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.ForProvider.Network.UUIDRef,
				Selector:     mg.Spec.ForProvider.Network.UUIDSelector,
				To:           reference.To{List: l, Managed: m},
			})
		}
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.Network.UUID")
		}
		mg.Spec.ForProvider.Network.UUID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.Network.UUIDRef = rsp.ResolvedReference

	}
	if mg.Spec.InitProvider.Network != nil {
		{
			m, l, err = apisresolver.GetManagedResource("network.upcloud.m.crossplane.io", "v1alpha1", "Network", "NetworkList")
			if err != nil {
				return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
			}
			rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Network.UUID),
				Extract:      reference.ExternalName(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.InitProvider.Network.UUIDRef,
				Selector:     mg.Spec.InitProvider.Network.UUIDSelector,
				To:           reference.To{List: l, Managed: m},
			})
		}
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.Network.UUID")
		}
		mg.Spec.InitProvider.Network.UUID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.Network.UUIDRef = rsp.ResolvedReference

	}

	return nil
}

// ResolveReferences of this FileStorageShare.
func (mg *FileStorageShare) ResolveReferences(ctx context.Context, c client.Reader) error {
	var m xpresource.Managed
	var l xpresource.ManagedList
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error
	{
		m, l, err = apisresolver.GetManagedResource("storage.upcloud.m.crossplane.io", "v1alpha1", "FileStorage", "FileStorageList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.FileStorage),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.FileStorageRef,
			Selector:     mg.Spec.ForProvider.FileStorageSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.FileStorage")
	}
	mg.Spec.ForProvider.FileStorage = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.FileStorageRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this FileStorageShareACL.
func (mg *FileStorageShareACL) ResolveReferences(ctx context.Context, c client.Reader) error {
	var m xpresource.Managed
	var l xpresource.ManagedList
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error
	{
		m, l, err = apisresolver.GetManagedResource("storage.upcloud.m.crossplane.io", "v1alpha1", "FileStorage", "FileStorageList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.FileStorage),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.FileStorageRef,
			Selector:     mg.Spec.ForProvider.FileStorageSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.FileStorage")
	}
	mg.Spec.ForProvider.FileStorage = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.FileStorageRef = rsp.ResolvedReference
	{
		m, l, err = apisresolver.GetManagedResource("storage.upcloud.m.crossplane.io", "v1alpha1", "FileStorageShare", "FileStorageShareList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ShareName),
			Extract:      common.ObservedExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.ShareNameRef,
			Selector:     mg.Spec.ForProvider.ShareNameSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ShareName")
	}
	mg.Spec.ForProvider.ShareName = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ShareNameRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this StorageBackup.
func (mg *StorageBackup) ResolveReferences(ctx context.Context, c client.Reader) error {
	var m xpresource.Managed
	var l xpresource.ManagedList
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error
	{
		m, l, err = apisresolver.GetManagedResource("storage.upcloud.m.crossplane.io", "v1alpha1", "Storage", "StorageList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.SourceStorage),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.SourceStorageRef,
			Selector:     mg.Spec.ForProvider.SourceStorageSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.SourceStorage")
	}
	mg.Spec.ForProvider.SourceStorage = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.SourceStorageRef = rsp.ResolvedReference
	{
		m, l, err = apisresolver.GetManagedResource("storage.upcloud.m.crossplane.io", "v1alpha1", "Storage", "StorageList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.SourceStorage),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.SourceStorageRef,
			Selector:     mg.Spec.InitProvider.SourceStorageSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.SourceStorage")
	}
	mg.Spec.InitProvider.SourceStorage = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.SourceStorageRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this StorageTemplate.
func (mg *StorageTemplate) ResolveReferences(ctx context.Context, c client.Reader) error {
	var m xpresource.Managed
	var l xpresource.ManagedList
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error
	{
		m, l, err = apisresolver.GetManagedResource("storage.upcloud.m.crossplane.io", "v1alpha1", "Storage", "StorageList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.SourceStorage),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.SourceStorageRef,
			Selector:     mg.Spec.ForProvider.SourceStorageSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.SourceStorage")
	}
	mg.Spec.ForProvider.SourceStorage = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.SourceStorageRef = rsp.ResolvedReference
	{
		m, l, err = apisresolver.GetManagedResource("storage.upcloud.m.crossplane.io", "v1alpha1", "Storage", "StorageList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.SourceStorage),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.SourceStorageRef,
			Selector:     mg.Spec.InitProvider.SourceStorageSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.SourceStorage")
	}
	mg.Spec.InitProvider.SourceStorage = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.SourceStorageRef = rsp.ResolvedReference

	return nil
}
